// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: compliance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreenTransactionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	SenderWallet   string                 `protobuf:"bytes,2,opt,name=sender_wallet,json=senderWallet,proto3" json:"sender_wallet,omitempty"`
	ReceiverWallet string                 `protobuf:"bytes,3,opt,name=receiver_wallet,json=receiverWallet,proto3" json:"receiver_wallet,omitempty"`
	Amount         float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	UserId         string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserFullName   string                 `protobuf:"bytes,7,opt,name=user_full_name,json=userFullName,proto3" json:"user_full_name,omitempty"`
	// NEW fields for Travel Rule
	RequiresTravelRule bool   `protobuf:"varint,8,opt,name=requires_travel_rule,json=requiresTravelRule,proto3" json:"requires_travel_rule,omitempty"`
	BeneficiaryName    string `protobuf:"bytes,9,opt,name=beneficiary_name,json=beneficiaryName,proto3" json:"beneficiary_name,omitempty"` // The person receiving the money
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScreenTransactionRequest) Reset() {
	*x = ScreenTransactionRequest{}
	mi := &file_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenTransactionRequest) ProtoMessage() {}

func (x *ScreenTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenTransactionRequest.ProtoReflect.Descriptor instead.
func (*ScreenTransactionRequest) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ScreenTransactionRequest) GetSenderWallet() string {
	if x != nil {
		return x.SenderWallet
	}
	return ""
}

func (x *ScreenTransactionRequest) GetReceiverWallet() string {
	if x != nil {
		return x.ReceiverWallet
	}
	return ""
}

func (x *ScreenTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ScreenTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ScreenTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScreenTransactionRequest) GetUserFullName() string {
	if x != nil {
		return x.UserFullName
	}
	return ""
}

func (x *ScreenTransactionRequest) GetRequiresTravelRule() bool {
	if x != nil {
		return x.RequiresTravelRule
	}
	return false
}

func (x *ScreenTransactionRequest) GetBeneficiaryName() string {
	if x != nil {
		return x.BeneficiaryName
	}
	return ""
}

type ScreenTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsApproved    bool                   `protobuf:"varint,1,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	RiskLevel     string                 `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	DiditRecordId string                 `protobuf:"bytes,3,opt,name=didit_record_id,json=diditRecordId,proto3" json:"didit_record_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenTransactionResponse) Reset() {
	*x = ScreenTransactionResponse{}
	mi := &file_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenTransactionResponse) ProtoMessage() {}

func (x *ScreenTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenTransactionResponse.ProtoReflect.Descriptor instead.
func (*ScreenTransactionResponse) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenTransactionResponse) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *ScreenTransactionResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ScreenTransactionResponse) GetDiditRecordId() string {
	if x != nil {
		return x.DiditRecordId
	}
	return ""
}

func (x *ScreenTransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_compliance_proto protoreflect.FileDescriptor

const file_compliance_proto_rawDesc = "" +
	"\n" +
	"\x10compliance.proto\x12\n" +
	"compliance\"\xdf\x02\n" +
	"\x18ScreenTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rsender_wallet\x18\x02 \x01(\tR\fsenderWallet\x12'\n" +
	"\x0freceiver_wallet\x18\x03 \x01(\tR\x0ereceiverWallet\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12$\n" +
	"\x0euser_full_name\x18\a \x01(\tR\fuserFullName\x120\n" +
	"\x14requires_travel_rule\x18\b \x01(\bR\x12requiresTravelRule\x12)\n" +
	"\x10beneficiary_name\x18\t \x01(\tR\x0fbeneficiaryName\"\xa8\x01\n" +
	"\x19ScreenTransactionResponse\x12\x1f\n" +
	"\vis_approved\x18\x01 \x01(\bR\n" +
	"isApproved\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12&\n" +
	"\x0fdidit_record_id\x18\x03 \x01(\tR\rdiditRecordId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2u\n" +
	"\x11ComplianceService\x12`\n" +
	"\x11ScreenTransaction\x12$.compliance.ScreenTransactionRequest\x1a%.compliance.ScreenTransactionResponseB-Z+github.com/PTGRAG/compliance-backend/pkg/pbb\x06proto3"

var (
	file_compliance_proto_rawDescOnce sync.Once
	file_compliance_proto_rawDescData []byte
)

func file_compliance_proto_rawDescGZIP() []byte {
	file_compliance_proto_rawDescOnce.Do(func() {
		file_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compliance_proto_rawDesc), len(file_compliance_proto_rawDesc)))
	})
	return file_compliance_proto_rawDescData
}

var file_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_compliance_proto_goTypes = []any{
	(*ScreenTransactionRequest)(nil),  // 0: compliance.ScreenTransactionRequest
	(*ScreenTransactionResponse)(nil), // 1: compliance.ScreenTransactionResponse
}
var file_compliance_proto_depIdxs = []int32{
	0, // 0: compliance.ComplianceService.ScreenTransaction:input_type -> compliance.ScreenTransactionRequest
	1, // 1: compliance.ComplianceService.ScreenTransaction:output_type -> compliance.ScreenTransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compliance_proto_init() }
func file_compliance_proto_init() {
	if File_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compliance_proto_rawDesc), len(file_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compliance_proto_goTypes,
		DependencyIndexes: file_compliance_proto_depIdxs,
		MessageInfos:      file_compliance_proto_msgTypes,
	}.Build()
	File_compliance_proto = out.File
	file_compliance_proto_goTypes = nil
	file_compliance_proto_depIdxs = nil
}
